#!/bin/bash
#SBATCH -N 1
#SBATCH -C gpu
#SBATCH -A mp309
#SBATCH -t 00:30:00
#SBATCH --gpus-per-node=1

conda activate scaling_diffusion
source ./setup_env.sh
python main.py   --pipeline_config_path="configs/sdxl.json"   --prompt="Photo of an athlete cat explaining it’s latest scandal at a press conference to journalists."   --num_prompts=None
